[request_definition]
r = sub, dom, obj, act  # subject(user), domain(tenant), object(resource), action

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _  # user X tiene rol Y en el tenant Z

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
